li = [('UK Core Publication (Version) History', '/guide/ukcoreversionhistory?version=current', 'Version history and development sequences for the UK Core'), ('UK Core Clinical and Technical Assurance Sprint 7 Documentation Pack', '/guide/ukcoreclinicalandtechnicalassurancedocumentationpack?version=current', 'This is the documentation pack for Sprint 7 of the UK Core Clinical and Technical Assurance.'), ('HL7 FHIR® UK Core Design and Development Approach', '/guide/hl7fhirukcoredesignanddevelopmentapproach?version=current', 'A guide outlining the design and development approach adopted for the UK Core.'), ('UK Core Implementation Guide Assets in Development', '/guide/ukcoreimplementationguideassetsindevelopment?version=current', 'This guide identifies those FHIR Assets that are in development and have not yet been through the UK Core Clinical and Technical Assurance process.'), ('UK Core Implementation Guide 1.0.0 - STU1', '/guide/uk-core-implementation-guide?version=current', 'Release 1.0.0 of the UK Core for STU1 Sequence following completion of HL7 UK Ballot 1'), ('UK Core Implementation Guidance Directory', '/guide/uk-core-implementation-guidance-directory?version=current', 'This guide provides a directory of information and guidance that will assist implementers of the UK Core.'), ('UK Core Hazard Log', '/guide/uk-core-hazard-log?version=current', 'This generic hazard logs captures the generic hazards for the UK Core.'), ('UK Core Implementation Guide STU3 Sequence', '/guide/uk-core-implementation-guide-stu3-sequence?version=current', 'Development build of the UK Core for STU3 Sequence '), ('UK Core Implementation Guide 2.0.1 - STU2 Sequence', '/guide/uk-core-implementation-guide-stu2?version=current', 'The UK Core for STU2 Sequence ballot, by HL7 UK'), ('HL7 FHIR® CareConnect Baseline Profiles for STU3 (Draft Standard for Trial Use)', '/guide/hl7fhircareconnectprofilesstu3?version=current', 'HL7 FHIR® CareConnect Baseline Profiles for STU3 (Draft Standard for Trial Use).  The goal of the CareConnect project is to adapt the HL7® FHIR® standard (version STU3) and create a library of profiles that implementers can adopt to simplify integration and interoperability within UK Health and Social Care.'), ('CareConnect Version History', '/guide/careconnectversionhistory?version=current', 'No description'), ('UK Naming Systems ', '/guide/uknamingsystems?version=current', 'UK FHIR Naming System Implementation Guide')]
li.sort()
print(li[0][0])
top_list = []
bottom_list = []
for tup in li:
    if 'UK Core Implementation Guide' in tup[0] and 'Development' not in tup[0]:
        top_list.append(tup)
    else:
        bottom_list.append(tup)
top_list = sorted(top_list,reverse=True)
bottom_list = sorted(bottom_list)
print(f"top: {top_list}\nlist: {bottom_list}")

