- name: Checkout all repositories from master_variables

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.repository.full_name }}
          ref: ${{ github.event.ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
  run: |
    python -c "
    import json
    import subprocess
    with open('master_variables.json') as f:
        repos = json.load(f)['repo_list']
    for repo in repos:
        subprocess.run(['git', 'clone', repo])
    "
- name: Run asset scraper
  run: python asset_scraper.py

- name: Commit and push changes
  run: |
    git config --global user.name "GitHub Actions"
    git config --global user.email "actions@github.com"
    git add .
    git diff --quiet || git commit -m "Update asset markdown"
    git push

