name: IOPS-AssetScrapper-InteropRegistry

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  workflow_call:
  #push:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    name: AssetScrapper Interoperability Registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Checkout all repositories from master_variables
        run: |
         python -c 'import json; import subprocess; \
         with open("master_variables.json") as f: \
         repos = json.load(f)["repo_list"]; \
         for repo in repos: \
         subprocess.run(["git", "clone", repo])'

            "
      - name: Run asset scraper
        run: python asset_scraper.py



     
