- name: Checkout all repositories from master_variables
  run: |
    python -c "
    import json
    import subprocess
    with open('master_variables.json') as f:
        repos = json.load(f)['repo_list']
    for repo in repos:
        subprocess.run(['git', 'clone', repo])
    "
